# This workflow runs nighly builds for each package.
name: nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0'

jobs:
  pkgs:
    uses: ./.github/workflows/.pkgs.yml

  build:
    uses: ./.github/workflows/.build.yml
    needs:
      - pkgs
    strategy:
      fail-fast: false
      matrix:
        pkg: ${{ fromJson(needs.pkgs.outputs.list) }}
    with:
      name: ${{ matrix.pkg }}
      release: pushonly
      envs: |
        NIGHTLY_BUILD=1
    secrets: inherit
